### PR TITLE
NPA-1711: add format qualifier to search params to improve docs and update payload to be FHIR compliant

### PR DESCRIPTION
**Pull request by miiisterjim**
## Summary
Routine Change

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [x] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

### CODE REVIEW

**Comment by samuel-hollow1-nhsd** [comment]
@miiisterjim Are we ready to merge this?

**Comment by chris-young-12-nhs** [comment]
> @miiisterjim Are we ready to review and merge this?

@samuel-hollow1-nhsd I think we need to hold off on merging this until we are clear about whether we are responding to a request with what we get back from PDS as what we get back from PDS does not match the spec or the changes in this PR. 

Specifically the code systems are different and there is an additional relationship of `Personal` which is returned from PDS but not part of the API spec. James has said on Slack that he has a meeting with IOPS on Friday afternoon - 15 March - to clarify this.

**Review by chris-young-12-nhs — APPROVED** [review]
LGTM

**Review by chris-young-12-nhs — APPROVED** [review]
LGTM

**Comment by chris-young-12-nhs** [comment]
LGTM

**Pull request merged**
